### ISSUE TITLE
US-0001 - Seguidor ou seguido não existente retorna NullPointer

### ISSUE THREAD

**Issue by JhonasML** [nathanformentin/desafio-spring#11]
Seguir não existente -> 500 java.lang.NullPointerException: Cannot invoke \"com.mercadolivre.desafio_spring.entity.User.getFollowers()\" because \"userToFollow\" is null\n\tat com.mercadolivre.desafio_spring.service.UserService.follow(UserService.java:34)

Não existir user1 -> java.lang.NullPointerException: Cannot invoke \"com.mercadolivre.desafio_spring.entity.User.getFollowed()\" because \"userFollowing\" is null\n\tat com.mercadolivre.desafio_spring.service.UserService.follow(UserService.java:33)

**Comment by nathanformentin** [comment]
Resolvido no commit (https://github.com/nathanformentin/desafio-spring/commit/7786ce7a698c245fb8a92fc564f07da58360f37c)
