### ISSUE TITLE
US-0002 Usuario não existente dando 500

### ISSUE THREAD

**Issue by JhonasML** [nathanformentin/desafio-spring#12]
sem existir -> 500 java.lang.NullPointerException: Cannot invoke \"com.mercadolivre.desafio_spring.entity.User.getFollowers()\" because \"user\" is null\n\tat com.mercadolivre.desafio_spring.service.UserService.countFollowers(UserService.java:57)\

**Comment by nathanformentin** [comment]
Resolvido no commit (https://github.com/nathanformentin/desafio-spring/commit/7786ce7a698c245fb8a92fc564f07da58360f37c)
