### ISSUE TITLE
US-0003 Usuario não existente dando 500

### ISSUE THREAD

**Issue by JhonasML** [nathanformentin/desafio-spring#13]
não existe -> 500 java.lang.NullPointerException: Cannot invoke \"com.mercadolivre.desafio_spring.entity.User.getFollowers()\" because \"user\" is null\n\tat com.mercadolivre.desafio_spring.service.UserService.getFollowers(UserService.java:66)

**Comment by nathanformentin** [comment]
Resolvido no commit (https://github.com/nathanformentin/desafio-spring/commit/7786ce7a698c245fb8a92fc564f07da58360f37c)
