### ISSUE TITLE
US-0004 Usuário não existente retorna 500

### ISSUE THREAD

**Issue by JhonasML** [nathanformentin/desafio-spring#14]
não existe 500 "java.lang.NullPointerException: Cannot invoke \"com.mercadolivre.desafio_spring.entity.User.getFollowed()\" because \"user\" is null\n\tat com.mercadolivre.desafio_spring.service.UserService.getFollowed(UserService.java:75)

**Comment by nathanformentin** [comment]
Resolvido no commit (https://github.com/nathanformentin/desafio-spring/commit/7786ce7a698c245fb8a92fc564f07da58360f37c)
