### ISSUE TITLE
US-0007 Seguidor e seguid não existe dando erro 500

### ISSUE THREAD

**Issue by JhonasML** [nathanformentin/desafio-spring#21]
1 seguidor nao existe
java.lang.NullPointerException: Cannot invoke \"com.mercadolivre.desafio_spring.entity.User.getFollowed()\" because \"userFollowing\" is null\n\tat com.mercadolivre.desafio_spring.service.UserService.unfollow(UserService.java:46)\n\tat com.mercadolivre.desafio_spring.controller.UserController.unfollow(UserController.java:32)\n\

2 seguido não existe 
"java.lang.NullPointerException: Cannot invoke \"com.mercadolivre.desafio_spring.entity.User.getFollowers()\" because \"userToUnfollow\" is null\n\tat com.mercadolivre.desafio_spring.service.UserService.unfollow(UserService.java:47)\

**Comment by nathanformentin** [comment]
Resolvido no commit (https://github.com/nathanformentin/desafio-spring/commit/7786ce7a698c245fb8a92fc564f07da58360f37c)
